#!/bin/sh

if [[ "$1" != "-p" ]]; then
    WORKDIR=${XDG_CONFIG_HOME:-$HOME/.config}/hmcl
    mkdir -p $WORKDIR
    cd $WORKDIR
fi

exec  /usr/lib/jvm/java-17-openjdk-17.*.x86_64/bin/java -jar "/usr/share/hmcl/hmcl.jar" "$@"


